export const PROCESS_HEARTBEAT_INTERVAL_MS = 10_000;
export const PROCESS_STALE_AFTER_MS = 45_000;
export const OPERATIONS_DEFAULT_EVENT_LIMIT = 20;
export const RECENT_CRITICAL_EVENT_WINDOW_MS = 30 * 60_000;
